### ISSUE TITLE
Menu in Action-Column in Datagrids is not opening properly

### ISSUE THREAD

**Issue by arctix-tk** [KaaschNicolas/Awp_Bosch#35]
When opening and closing the Menu in the Action-Column inside a DataGrid multiple times, the Menu does not open properly. after double clicking on the "Open"-Button the Menu works as intended again.

**Comment by scda1092** [comment]
Can we list the action in a row for now, so we don´t have to open any menu in the DataGrid.

This way we could get some momentum on other tasks. Converting it back to a menu shouldn´t be to hard. And fixing it could be a future task for another sprint or if we got some time left in between sprints.

**Comment by fasa1016** [comment]
Ich habe mal das ganze getestet, ein möglicher Workaround könnte sein, wenn man nach fokusieren der Action-Zelle (= Aufruf des Action-Buttons) den Fokus aus der Zelle verliert.
Zumindest ist der Fehler in dieser Konstellation nicht mehr aufgetreten. 
Ich versuche einen Fix zu implementieren.

**Comment by fasa1016** [comment]
> Ich habe mal das ganze getestet, ein möglicher Workaround könnte sein, wenn man nach fokusieren der Action-Zelle (= Aufruf des Action-Buttons) den Fokus aus der Zelle verliert. Zumindest ist der Fehler in dieser Konstellation nicht mehr aufgetreten. Ich versuche einen Fix zu implementieren.

Ich korrigiere, Verhalten wurde mit dem Ansatz nur schlimmer :)

**Comment by fasa1016** [comment]
Die Property ` AllowFocusOnInteraction="True">` für jedes AppBarButton-Element in der xaml scheint das Problem zu lösen.
